apiVersion: v1
kind: Service
metadata:
  name: trivy-service
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/instance: trivy-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/instance: trivy-server
  ports:
    - name: trivy-http
      protocol: TCP
      port: 4954
      targetPort: 4954
  sessionAffinity: ClientIP
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trivy-server
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-server
    app.kubernetes.io/instance: trivy-server
spec:
  podManagementPolicy: "Parallel"
  serviceName: trivy-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trivy-server
      app.kubernetes.io/instance: trivy-server
  template:
    metadata:
      annotations:
        checksum/config: 7fcc66ace3f98462349856795765021e7bf7a0106f28439a9f6dc74257404370
      labels:
        app.kubernetes.io/name: trivy-server
        app.kubernetes.io/instance: trivy-server
    spec:
      containers:
        - name: trivy-server
          image: "docker.io/aquasec/trivy:0.63.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - server
          ports:
            - name: trivy-http
              containerPort: 4954
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: trivy-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: trivy-http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-data
              readOnly: false
            - mountPath: /home/scanner/.cache
              name: data
              readOnly: false
      volumes:
        - name: tmp-data
          emptyDir: {}
        - name: data
          emptyDir: {}

